include: package:effective_dart/analysis_options.1.3.0.yaml

linter:
  rules:
    avoid_catches_without_on_clauses: true
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: true
    avoid_relative_lib_imports: true
    implementation_imports: true
    lines_longer_than_80_chars: false
    one_member_abstracts: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_relative_imports: true
    public_member_api_docs: false
    require_trailing_commas: true
    unnecessary_lambdas: true
    unnecessary_brace_in_string_interps: true

analyzer:
  exclude:
