name: kanji_dictionary
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.11.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: 0.13.5
  firebase_auth: 0.15.4
  firebase_ml_vision: 0.9.3+8
  html: 0.14.0+2
  http: 0.12.0+4
  rxdart: 0.23.1
  sqflite: 1.1.5
  path_provider: 1.1.0
  shared_preferences: 0.5.2
  image_picker: 0.6.5
  url_launcher: 5.4.1
  apple_sign_in: ^0.1.0
  app_review: 1.1.0+1
  googleapis: 0.55.0
  googleapis_auth: 0.2.11+1
  google_sign_in: 4.4.6
  connectivity: 0.4.8+2
  permission_handler: 5.0.0+hotfix.3
  tflite: 1.0.5
  video_player: 0.10.9
  uuid: 2.0.4
  flutter_device_type: 0.2.0
  font_awesome_flutter:
    path: ./font_awesome_flutter/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
  - family: kazei
    fonts:
    - asset: fonts/kazei.ttf
  - family: Ai
    fonts:
    - asset: fonts/AiharaHudemojiKaisho3.00.ttf
  - family: strokeOrders
    fonts:
    - asset: fonts/KanjiStrokeOrders.ttf
  - family: ming
    fonts:
      - asset: fonts/HiraginoMin-W4-90-RKSJ-H-2.ttc

  assets:
  - data/data
  - data/dictDB.db
  - data/matts.png
  - data/ic_launcher_round.png
  - data/ic_launcher-web.png
  - data/1024.png
  - data/left.png
  - data/right.png
  - data/labels.txt
  - data/model.tflite
  - data/im.png
  - video/