name: kanji_dictionary
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+28

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore:
  collection:
  firebase_core:
  firebase_auth: 1.0.1
  google_sign_in: 4.4.6
  html: 0.14.0+2
  http: 0.13.1
  rxdart: 0.26.0
  sqflite: 2.0.0+2
  path_provider: 1.1.0
  shared_preferences:
  image_picker: 0.6.5
  image: 3.0.2
  url_launcher: 6.0.3
  apple_sign_in: ^0.1.0
  font_awesome_flutter:
    path: ./font_awesome_flutter/
  app_review: 2.1.1+1
  googleapis: 2.0.0
  googleapis_auth: 1.1.0
  connectivity: 3.0.3
  permission_handler: 6.1.1
  tflite: 1.0.5
  video_player: 2.1.0
  uuid: 3.0.3
  flutter_device_type: 0.2.0
  flutter_siri_suggestions: 1.0.2+hotfix1
  vibration: 1.4.0
  confetti: 0.5.4
  flutter_tts: 1.2.6
  feature_discovery: 0.13.0+2
  in_app_purchase: 0.5.1+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
  - family: kazei
    fonts:
    - asset: fonts/kazei.ttf
  - family: Ai
    fonts:
    - asset: fonts/AiharaHudemojiKaisho3.00.ttf
  - family: strokeOrders
    fonts:
    - asset: fonts/KanjiStrokeOrders.ttf
  - family: ming
    fonts:
      - asset: fonts/HiraginoMin-W4-90-RKSJ-H-2.ttc

  assets:
  - data/data
  - data/dictDB.db
  - data/matts.png
  - data/ic_launcher_round.png
  - data/ic_launcher-web.png
  - data/1024.png
  - data/left.png
  - data/right.png
  - data/labels.txt
  - data/model.tflite
  - data/im.png
  - video/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
